### PR TITLE
docs: memory safety

### PR DESCRIPTION
**Pull request by scolsen**

### CODE REVIEW

**Comment by Magnogen** [comment]
Hahah, although I was skeptical about memory safely, this is actually brilliant!

**Comment by TodePond** [comment]
lgtm!

i like the idea of using lots of exclamation marks!!!!!!

I might edit it to be a bit simpler before merging tomorrow :)

**Comment by scolsen** [comment]
Thanks @TodePond! and thanks for all your work on this beautiful language

**Comment by TodePond** [comment]
I think perhaps:

* Multiple exclamation marks could be used more generally to overload stuff.
Like:
```
const name = "Lu"!!!
const name = "Luke"!

print(name) // "Lu"
```

* Using 'computer memory' more literally could be its own fun thing.

**Comment by Magnogen** [comment]
It's like `!important` in CSS but better

**Pull request merged**
