### PR TITLE
fixed boolean value

### PR DESCRIPTION
**Pull request by Colon101**
since new users reading the dreamberd readme file do not know that strings can have 0 qoutation marks at that point it is difficult to understand this line of code with the inconsistancy of the boolean values

this is a simple fix changing

`True`
to 
`true`

### CODE REVIEW

**Comment by TodePond** [comment]
this is intentionally a string value here because it results in a PR like this every month or so

**Comment by Colon101** [comment]
I understand that but i think there is a different issue now
you havent told them the fact that you can use 0 qoutes beforehand which may cause confusion for readers ༼ つ ◕_◕ ༽つ

**Comment by TodePond** [comment]
i don't see the problem

**Review by Endermanbugzjfc — CHANGES_REQUESTED** [review]
million dollar mistake

**Pull request closed without merging**
