### PR TITLE
Show feed quality

### PR DESCRIPTION
**Pull request by mybearworld**
Adds the following badge to the feed: 
The significance of this number is left as an exercise to the reader.

### CODE REVIEW

**Comment by loglot** [comment]
the image should be hosted on the repo

**Comment by mybearworld** [comment]
> the image should be hosted on the repo

Why?

**Comment by loglot** [comment]
You told me that same thing

**Comment by mybearworld** [comment]
> You told me that same thing

I did, but the image was uploaded in GitHub under your name. This was done before, and the link broke. However, this is a [shields.io](https://shields.io)-hosted image, which won't break and is where most shields are hosted.

**Comment by loglot** [comment]
I see

**Comment by mybearworld** [comment]
No longer applies

**Pull request closed without merging**
