### PR TITLE
add semantic naming to variables

### PR DESCRIPTION
**Pull request by nonchris**
As a proud investor of the first hour, I'm fully invested to make the most of my 0,69 £.   
This kept me on the edge of my seat day and night - until now!  
Now I'm confident that I found the \*perfect\* contribution to the greatest programming language ever created by mankind.  
So I'd love ti present add my humble contribution to DreamBerds specifications.

## introducing: "Semantic Naming" of variables!
I guess the commit itself speaks volumes.  
More than my words could ever tell.  
please have a look yourself and consider this as my contribution to mankind.

(now as a signed-commit version)

### CODE REVIEW

**Comment by TodePond** [comment]
Ok this is actually really good. I feel like it could go harder on the hungarian notation naming insanity. Love those one letter prefixes like `bBool`, `iInt`, etc...

I think the description could be more to the point, like one sentence only. `DreamBerd supports hungarian notation` or something 🤔

(just thinking aloud)

**Comment by nonchris** [comment]
hehe, thanks :D   
uh, actually never heard of that convention. just googled it - I see what you mean.  
if we lean to much in it it might reach a point where you could even argue that it's actually useful - and I guess we don't want that here, right? ^^'

and yeah, we could probably shorten the description. I'm not that good at keeping it short (:

**Comment by nonchris** [comment]
I made some changes.   
now we've got Hungarian notation in the examples (makes the example even more confusing) and I cut one sentence.   
The readers will notice the usage of `!`and `?` without explanation :)

**Comment by nonchris** [comment]
@TodePond what do you think 'bout these changes?

**Review by TodePond — COMMENTED** [review]
I think it would benefit from simplifying a lot. It's a funny joke on its own so any extra text distracts from it.

I think that ambiguity of whether it makes any difference would be good. It lets people use their imagination about what it does.

I also think it should be moved later on. Definitely after the "types" section. Maybe way later than that.

Here's a suggested edit:



## Semantic naming

DreamBerd supports semantic naming.

```java
const const sName = "Lu"!
const const iAge = 29!
const const bHappy = true!
```

**New for 2023:** You can now make globals.

```java
const const g_fScore = 4.5!
```

**Pull request merged**
