### PR TITLE
Add 'GOTO and COMEFROM' section

### LINKED ISSUE #99: goto statement
I'd like a goto statement that accepts a string or other code.

```java
const var keys = {}!
addEventListener("keydown", e => keys[e.key] = true)!
addEventListener("keyup", e => keys[e.key] = false)!

function isKeyDown(key) => {
   if (keys[key] = undefined) {
       goto(const var keys = {}!)
   }
}
```

### PR DESCRIPTION
**Pull request by Ezlanding1**
Resolves #99 by adding a 'goto' and 'comefrom' statement

### CODE REVIEW

**Comment by arily** [comment]
is the line number relative to the statement, or from start of the file?

**Comment by Ezlanding1** [comment]
> is the line number relative to the statement, or from start of the file?

From the start of the file

**Comment by plutoniumm** [comment]
this feature could potentially introduce loops thus re-introducing the long abandoned archaic idea

**Comment by Ezlanding1** [comment]
I agree that loops are an anti-pattern, however TodePond seemed to approve the example use of goto in issue #99, which allowed for loops. If it is preferred, I’ll change the spec to only allow jumping forward in execution.

**Comment by TodePond** [comment]
yes technically this isn't a loop. it's a repetition, which is fine

**Pull request closed without merging**
