### PR TITLE
Add some random badges so that the repo looks legit

### PR DESCRIPTION
**Pull request by naveen17797**

### CODE REVIEW

**Comment by stohrendorf** [comment]
I think 100% coverage is a little too low. Also, I think it's missing both a legit badge and a badge that counts the number of badges, as well as a badge counter badge counter.

**Comment by naveen17797** [comment]
I agree! The badge counter should be a made as a microservice so that it can scale rapidly. I propose we add a kafka queue which will listen to events from repo. We can also have a postgres database which does the same function as kafka queue so that we ensure that we will never lose the events.

**Comment by stohrendorf** [comment]
One issue, though, the bade counter doesn't count itself. With the badge counter, there are 9 badges now, not 8 as it says.

**Comment by naveen17797** [comment]
But arrays start at 0, so it should be 8

**Comment by stohrendorf** [comment]
Arrays in DreamBerd start at -1 ;)

**Comment by flexagoon** [comment]
There should be a badge with a fake icon and service name, something like

[⚡ CodeZapper | Platinum level]

**Comment by TodePond** [comment]
I really like this idea :)
I think that having just one badge would be great. I think it would have more impact like that. My favourite is the coverage one! Something like `Coverage | 109%` might be fun.

**Comment by naveen17797** [comment]
sure.

**Comment by mindplay-dk** [comment]
> I'd be happy to merge a single badge btw :)

one badge... "badge count: 1" 😏

**Comment by rpkak** [comment]
cov

**Pull request closed without merging**
