### PR TITLE
1.5 bits are not enough for a boolean

### PR DESCRIPTION
**Pull request by ritschwumm**
log2(3) is about 1.58496250072

### CODE REVIEW

**Comment by TodePond** [comment]
it's ok it can be 1.5 because they're always stored in pairs, just rearranged

**Comment by TodePond** [comment]
```
000 false false
001 false maybe
010 maybe maybe
011 (unused)
100 true false
101 (unused)
110 true maybe
111 true true
```

**Comment by ritschwumm** [comment]
how about false true? i'd expect 3^2 = 9 combinations

**Comment by TodePond** [comment]
for false true just use true false and swap the references around

**Comment by ritschwumm** [comment]
ok...

**Pull request closed without merging**
